[package]
name = "ironside-task"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = "0.2.2"
